---
title: "Exercise 6"
author: "Matthew Reynolds"
date: "2023-04-19"
output: html_notebook
---

<b>Question:</b>\
Suppose we collect data for a group of students in a statistics class with variables X1 = hours studied, X2 = undergrad GPA, and Y = receive an A. We fit a logistic regression and produce estimated coefficient, βˆ0 = −6, βˆ1 = 0.05, βˆ2 = 1.\
<div style="padding-left: 20px;">
  <p>(a) Estimate the probability that a student who studies for 40 h and has an undergrad GPA of 3.5 gets an A in the class.</p>
  <p><b>Answer:</b> \
  Since we're given: $\hat{\beta}_{0}$ = −6, $\hat{\beta}_{1}$ = 0.05, $\hat{\beta}_{2}$ = 1, and $X_{1}$ = 40 and $X_{2}$ = 3.5.
  We simply plug the values in to our equation and solve. \
  $-6 + 0.05(40) + 1(3.5)$ \
  Which results in: \
  $-0.5$ \
  We plug that into our next equation:
  $\large \frac{e^k}{1 + e^k}$ \
  So: \
  $\large \frac{e^{-0.5}}{1 + e^{-0.5}}$ \
  \
  Which results in: \
  $37.75$% chance of getting an A in the class given the 40 hours of studying and a undergrad GPA of 3.5
  </p>
</div>

<div style="padding-left: 20px;">
  <p>(b) How many hours would the student in part (a) need to study to have a 50 % chance of getting an A in the class?</p>
  <p><b>Answer:</b>
  We take our previous equation:  $\large \frac{e^k}{1 + e^k}$ and set it equal to 1/2.
   $\large \frac{e^k}{1 + e^k} = \frac{1}{2}$ \
   \
   $1+e^k = 2e^k$ \
   \
   $1 = e^k$ \
   \
   $ln(1) = ln(e^k)$ \
   \
   $0 = k$ \
   \
   So with our new value of k, we set our other equation for the Betas equal to it. \
   $-6 + 0.05(X_{1}) + 1(3.5) = 0$ \
   \
   $-2.5 + 0.05(X_{1} = 0$ \
   \
   $0.05(X_{1}) = 2.5$\
   \
   $X_{1} = \frac{2.5}{0.05}$ \
   \
   $X_{1} = 50$\
   \
   Therefore it would take our student from part A 50 hours to achieve a 50% probability of getting an A in their course.
  </p>
</div>
  